"""init schema

Revision ID: 1d9fe3a23452
Revises: 
Create Date: 2026-07-24 15:53:47.217095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d9fe3a23452'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keel_api',
    sa.Column('path', sa.String(length=200), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('tags', sa.String(length=100), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keel_api_created_at'), 'keel_api', ['created_at'], unique=False)
    op.create_index(op.f('ix_keel_api_is_active'), 'keel_api', ['is_active'], unique=False)
    op.create_index(op.f('ix_keel_api_is_deleted'), 'keel_api', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_keel_api_updated_at'), 'keel_api', ['updated_at'], unique=False)
    op.create_index(op.f('ix_keel_api_uuid'), 'keel_api', ['uuid'], unique=True)
    op.create_table('keel_audit_log',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('module', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.String(length=128), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('host', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('response_time', sa.Integer(), nullable=True),
    sa.Column('request_args', sa.JSON(), nullable=True),
    sa.Column('response_body', sa.JSON(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keel_audit_log_created_at'), 'keel_audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_keel_audit_log_is_active'), 'keel_audit_log', ['is_active'], unique=False)
    op.create_index(op.f('ix_keel_audit_log_is_deleted'), 'keel_audit_log', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_keel_audit_log_updated_at'), 'keel_audit_log', ['updated_at'], unique=False)
    op.create_index(op.f('ix_keel_audit_log_uuid'), 'keel_audit_log', ['uuid'], unique=True)
    op.create_table('keel_depts',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('desc', sa.String(length=500), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keel_depts_created_at'), 'keel_depts', ['created_at'], unique=False)
    op.create_index(op.f('ix_keel_depts_is_active'), 'keel_depts', ['is_active'], unique=False)
    op.create_index(op.f('ix_keel_depts_is_deleted'), 'keel_depts', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_keel_depts_name'), 'keel_depts', ['name'], unique=True)
    op.create_index(op.f('ix_keel_depts_order'), 'keel_depts', ['order'], unique=False)
    op.create_index(op.f('ix_keel_depts_parent_id'), 'keel_depts', ['parent_id'], unique=False)
    op.create_index(op.f('ix_keel_depts_updated_at'), 'keel_depts', ['updated_at'], unique=False)
    op.create_index(op.f('ix_keel_depts_uuid'), 'keel_depts', ['uuid'], unique=True)
    op.create_table('keel_file',
    sa.Column('file_id', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('upload_user_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keel_file_created_at'), 'keel_file', ['created_at'], unique=False)
    op.create_index(op.f('ix_keel_file_file_id'), 'keel_file', ['file_id'], unique=True)
    op.create_index(op.f('ix_keel_file_is_active'), 'keel_file', ['is_active'], unique=False)
    op.create_index(op.f('ix_keel_file_is_deleted'), 'keel_file', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_keel_file_updated_at'), 'keel_file', ['updated_at'], unique=False)
    op.create_index(op.f('ix_keel_file_upload_user_id'), 'keel_file', ['upload_user_id'], unique=False)
    op.create_index(op.f('ix_keel_file_uuid'), 'keel_file', ['uuid'], unique=True)
    op.create_table('keel_item',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keel_item_created_at'), 'keel_item', ['created_at'], unique=False)
    op.create_index(op.f('ix_keel_item_is_active'), 'keel_item', ['is_active'], unique=False)
    op.create_index(op.f('ix_keel_item_is_deleted'), 'keel_item', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_keel_item_name'), 'keel_item', ['name'], unique=False)
    op.create_index(op.f('ix_keel_item_updated_at'), 'keel_item', ['updated_at'], unique=False)
    op.create_index(op.f('ix_keel_item_uuid'), 'keel_item', ['uuid'], unique=True)
    op.create_table('keel_menu',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('remark', sa.JSON(), nullable=True),
    sa.Column('menu_type', sa.String(length=20), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('path', sa.String(length=100), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('component', sa.String(length=100), nullable=True),
    sa.Column('keepalive', sa.Boolean(), nullable=False),
    sa.Column('redirect', sa.String(length=100), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keel_menu_created_at'), 'keel_menu', ['created_at'], unique=False)
    op.create_index(op.f('ix_keel_menu_is_active'), 'keel_menu', ['is_active'], unique=False)
    op.create_index(op.f('ix_keel_menu_is_deleted'), 'keel_menu', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_keel_menu_updated_at'), 'keel_menu', ['updated_at'], unique=False)
    op.create_index(op.f('ix_keel_menu_uuid'), 'keel_menu', ['uuid'], unique=True)
    op.create_table('keel_role',
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('desc', sa.String(length=500), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keel_role_created_at'), 'keel_role', ['created_at'], unique=False)
    op.create_index(op.f('ix_keel_role_is_active'), 'keel_role', ['is_active'], unique=False)
    op.create_index(op.f('ix_keel_role_is_deleted'), 'keel_role', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_keel_role_updated_at'), 'keel_role', ['updated_at'], unique=False)
    op.create_index(op.f('ix_keel_role_uuid'), 'keel_role', ['uuid'], unique=True)
    op.create_table('keel_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keel_settings_created_at'), 'keel_settings', ['created_at'], unique=False)
    op.create_index(op.f('ix_keel_settings_is_active'), 'keel_settings', ['is_active'], unique=False)
    op.create_index(op.f('ix_keel_settings_is_deleted'), 'keel_settings', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_keel_settings_key'), 'keel_settings', ['key'], unique=True)
    op.create_index(op.f('ix_keel_settings_updated_at'), 'keel_settings', ['updated_at'], unique=False)
    op.create_index(op.f('ix_keel_settings_uuid'), 'keel_settings', ['uuid'], unique=True)
    op.create_table('keel_user',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('alias', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keel_user_created_at'), 'keel_user', ['created_at'], unique=False)
    op.create_index(op.f('ix_keel_user_is_active'), 'keel_user', ['is_active'], unique=False)
    op.create_index(op.f('ix_keel_user_is_deleted'), 'keel_user', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_keel_user_updated_at'), 'keel_user', ['updated_at'], unique=False)
    op.create_index(op.f('ix_keel_user_username'), 'keel_user', ['username'], unique=True)
    op.create_index(op.f('ix_keel_user_uuid'), 'keel_user', ['uuid'], unique=True)
    op.create_table('keel_role_api',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['keel_api.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['keel_role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'api_id')
    )
    op.create_table('keel_role_menu',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['keel_menu.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['keel_role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'menu_id')
    )
    op.create_table('keel_user_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['keel_role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['keel_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keel_user_role')
    op.drop_table('keel_role_menu')
    op.drop_table('keel_role_api')
    op.drop_index(op.f('ix_keel_user_uuid'), table_name='keel_user')
    op.drop_index(op.f('ix_keel_user_username'), table_name='keel_user')
    op.drop_index(op.f('ix_keel_user_updated_at'), table_name='keel_user')
    op.drop_index(op.f('ix_keel_user_is_deleted'), table_name='keel_user')
    op.drop_index(op.f('ix_keel_user_is_active'), table_name='keel_user')
    op.drop_index(op.f('ix_keel_user_created_at'), table_name='keel_user')
    op.drop_table('keel_user')
    op.drop_index(op.f('ix_keel_settings_uuid'), table_name='keel_settings')
    op.drop_index(op.f('ix_keel_settings_updated_at'), table_name='keel_settings')
    op.drop_index(op.f('ix_keel_settings_key'), table_name='keel_settings')
    op.drop_index(op.f('ix_keel_settings_is_deleted'), table_name='keel_settings')
    op.drop_index(op.f('ix_keel_settings_is_active'), table_name='keel_settings')
    op.drop_index(op.f('ix_keel_settings_created_at'), table_name='keel_settings')
    op.drop_table('keel_settings')
    op.drop_index(op.f('ix_keel_role_uuid'), table_name='keel_role')
    op.drop_index(op.f('ix_keel_role_updated_at'), table_name='keel_role')
    op.drop_index(op.f('ix_keel_role_is_deleted'), table_name='keel_role')
    op.drop_index(op.f('ix_keel_role_is_active'), table_name='keel_role')
    op.drop_index(op.f('ix_keel_role_created_at'), table_name='keel_role')
    op.drop_table('keel_role')
    op.drop_index(op.f('ix_keel_menu_uuid'), table_name='keel_menu')
    op.drop_index(op.f('ix_keel_menu_updated_at'), table_name='keel_menu')
    op.drop_index(op.f('ix_keel_menu_is_deleted'), table_name='keel_menu')
    op.drop_index(op.f('ix_keel_menu_is_active'), table_name='keel_menu')
    op.drop_index(op.f('ix_keel_menu_created_at'), table_name='keel_menu')
    op.drop_table('keel_menu')
    op.drop_index(op.f('ix_keel_item_uuid'), table_name='keel_item')
    op.drop_index(op.f('ix_keel_item_updated_at'), table_name='keel_item')
    op.drop_index(op.f('ix_keel_item_name'), table_name='keel_item')
    op.drop_index(op.f('ix_keel_item_is_deleted'), table_name='keel_item')
    op.drop_index(op.f('ix_keel_item_is_active'), table_name='keel_item')
    op.drop_index(op.f('ix_keel_item_created_at'), table_name='keel_item')
    op.drop_table('keel_item')
    op.drop_index(op.f('ix_keel_file_uuid'), table_name='keel_file')
    op.drop_index(op.f('ix_keel_file_upload_user_id'), table_name='keel_file')
    op.drop_index(op.f('ix_keel_file_updated_at'), table_name='keel_file')
    op.drop_index(op.f('ix_keel_file_is_deleted'), table_name='keel_file')
    op.drop_index(op.f('ix_keel_file_is_active'), table_name='keel_file')
    op.drop_index(op.f('ix_keel_file_file_id'), table_name='keel_file')
    op.drop_index(op.f('ix_keel_file_created_at'), table_name='keel_file')
    op.drop_table('keel_file')
    op.drop_index(op.f('ix_keel_depts_uuid'), table_name='keel_depts')
    op.drop_index(op.f('ix_keel_depts_updated_at'), table_name='keel_depts')
    op.drop_index(op.f('ix_keel_depts_parent_id'), table_name='keel_depts')
    op.drop_index(op.f('ix_keel_depts_order'), table_name='keel_depts')
    op.drop_index(op.f('ix_keel_depts_name'), table_name='keel_depts')
    op.drop_index(op.f('ix_keel_depts_is_deleted'), table_name='keel_depts')
    op.drop_index(op.f('ix_keel_depts_is_active'), table_name='keel_depts')
    op.drop_index(op.f('ix_keel_depts_created_at'), table_name='keel_depts')
    op.drop_table('keel_depts')
    op.drop_index(op.f('ix_keel_audit_log_uuid'), table_name='keel_audit_log')
    op.drop_index(op.f('ix_keel_audit_log_updated_at'), table_name='keel_audit_log')
    op.drop_index(op.f('ix_keel_audit_log_is_deleted'), table_name='keel_audit_log')
    op.drop_index(op.f('ix_keel_audit_log_is_active'), table_name='keel_audit_log')
    op.drop_index(op.f('ix_keel_audit_log_created_at'), table_name='keel_audit_log')
    op.drop_table('keel_audit_log')
    op.drop_index(op.f('ix_keel_api_uuid'), table_name='keel_api')
    op.drop_index(op.f('ix_keel_api_updated_at'), table_name='keel_api')
    op.drop_index(op.f('ix_keel_api_is_deleted'), table_name='keel_api')
    op.drop_index(op.f('ix_keel_api_is_active'), table_name='keel_api')
    op.drop_index(op.f('ix_keel_api_created_at'), table_name='keel_api')
    op.drop_table('keel_api')
    # ### end Alembic commands ###
